sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    #表示密码为空
    password: ""


  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tB8mDcfQk5xdHRrXZ8u
    access-key-secret: BLKlQSpxVpvC8YvhZyPs6ZuxjTn8LU
    bucket-name: xiyou-bucket


  redis:
    host: localhost
    port: 6379
    #表示密码为空
    password: ""
    #使用redis 16个库中的编号为10的库
    database: 10

  wechat:
    appid: wxb29987b155e8333a
    secret: 869e7dc23a266b94d246e4e0ce68dd9f